### PR TITLE
[New]: Provide both range and start & end property on Node, support eslint v7

### LINKED ISSUE #96: Support ESLint 7.x
ESLint v7.0.0 is [released](https://eslint.org/blog/2020/05/eslint-v7.0.0-released) 🎉

It would be awesome to have official ESLint 7 support. 👊
I'm happy to help where I can of course 🙂

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
(dev)Dependencies should be compatible with ESLint 7 too before we can merge this one:

- [x] [`eslint-config-airbnb-base`](https://github.com/airbnb/javascript/issues/2223)
  - [x]  [PR](https://github.com/airbnb/javascript/pull/2240)
  - [x]  [Release](https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/CHANGELOG.md#1420--2020-06-10)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
@evcohen @ljharb CI is passing here, but [supporting ESLint 7.x in `eslint-plugin-jsx-a11y`](https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/684) fails CI and [throws](https://travis-ci.org/github/evcohen/eslint-plugin-jsx-a11y/jobs/685017801) the following error when using `getPropValue` & `getLiteralPropValue `:

```sh
 Use node.range[0] instead of node.start
```

Can't figure out what causes this error though... 🤔
The only time I find `node.start` usage is in `getProp-parse-test`:
https://github.com/evcohen/jsx-ast-utils/blob/ef189952cf16c126202e0524565d8d5787908d20/__tests__/src/getProp-parser-test.js#L103

**Comment by MichaelDeBoey** [comment]
I've been doing some research and found out the [reason](https://github.com/eslint/rfcs/blob/master/designs/2019-rule-tester-improvements/README.md#1-disallowing-nodestart-and-nodeend) why they disallowed the usage `node.start` & `node.end`.

After disabling the return of both `node.start` & `node.end`, CI is failing on this side because `@babel/parser` is still returning them.
So I think this should be fixed on their side too I guess? 🤔

Another option would be to change the `deepStrictEqual` assert to a normal `deepEqual`, but that can cause other bugs I'm afraid.

**Comment by MichaelDeBoey** [comment]
I've been doing some research and found out the [reason](https://github.com/eslint/rfcs/blob/master/designs/2019-rule-tester-improvements/README.md#1-disallowing-nodestart-and-nodeend) why they disallowed the usage `node.start` & `node.end`.

After disabling the return of both `node.start` & `node.end`, CI is failing on this side because `@babel/parser` is still returning them.
So I think this should be fixed on their side too I guess? 🤔

Another option would be to change the `deepStrictEqual` assert to a normal `deepEqual`, but that can cause other bugs I'm afraid.

**Comment by MichaelDeBoey** [comment]
Giving this some thoughts and I think we should fix it on our end if we want to keep supporting Node@<6.x.
Even when `@babel/parser` fixes this, `babylon` will still keep failing CI then.

**Comment by ljharb** [comment]
Since this package only uses eslint as a dev dep, this PR isn't a feature; and it's blocked on the plugins it uses supporting eslint v7.

We definitely need to keep supporting the same node versions. In this case, we should find a way to configure the tests to use start/end only when it's allowed by RuleTester.

**Comment by MichaelDeBoey** [comment]
@evcohen @ljharb I've managed to change the code so that it doesn't return the non-standard `node.start` & `node.end` anymore.

Since it's non-standard and `estree` & `@typescript-eslint/parser` has already removed it completely, I think we should do too.

**Comment by MichaelDeBoey** [comment]
@evcohen @ljharb All tests are green 🙂

**Comment by MichaelDeBoey** [comment]
@ljharb That will indeed be a breaking change.
Can't think of a way to do this without making this a breaking change though 😕

**Comment by ljharb** [comment]
I don’t think it’s worth a breaking change to any package just so it can use a newer version of the linter - leaving this package on eslint 6 for the foreseeable future seems fine to me.

**Comment by MichaelDeBoey** [comment]
@ljharb That will break all ESLint plugins/configs (like `eslint-plugin-jsx-a11y`) that use this package if they want to support ESLint 7.
Those plugins/configs can cause other plugins or configs to fail supporting ESLint 7 too.

**Comment by ljharb** [comment]
I'm not sure why it would? it's RuleTester that can't use start/end, not plugins.

**Comment by MichaelDeBoey** [comment]
It's because `node.start`/`node.end` are non-standard and are mostly wrongly used.
They should never been used or been public.
That's why they're now deprecated.

`RuleTester` comes from the `eslint` package btw, so it's officially a deprecation error.

**Comment by ljharb** [comment]
Sure - but error or not, consumers will still *work*, no?

**Comment by MichaelDeBoey** [comment]
@ljharb Since it's a hard deprecation that's throwing an error, It won't.

**Comment by MichaelDeBoey** [comment]
Ping @ljharb

**Comment by ljharb** [comment]
It throws an error in RuleTester - it wouldn't throw one at runtime, since eslint itself doesn't interact with the code between this package and rules.

**Comment by MichaelDeBoey** [comment]
@ljharb Ant suggestion on how we can fix this then? 🤔

**Comment by ljharb** [comment]
I think we could revert the runtime removal of start/end, and then in the tests, skip the appropriate tests when eslint is 7+?

**Comment by MichaelDeBoey** [comment]
@ljharb If we can do this somehow, that will still fail tests in our dependencies, no? 🤔
Those will have to use the same trick all over again then, which is not really what they would want.

ESLint is pushing towards not using `.start` and `.end` anymore and will probably fully deprecate/remove them from espree in the future.
I don’t get why they didn’t do that right away though.

I think a breaking change for this package is justified, since people who don’t want or can’t update (yet), can still use the current version.
People who need to get rid of the `.start` and `.end` errors and don’t want to implement the whole trick you’re suggesting all over again can upgrade to the new version.

**Comment by ljharb** [comment]
That’s fine; dependents can change themselves to use the range property when using eslint 7. It wouldn’t fail our dependents using eslint 6.

In other words, because this package does not require eslint 7 - it works on both 6 and 7 - and start and end work fine in v6 - this package should continue to provide them.

**Comment by MichaelDeBoey** [comment]
@ljharb That's the whole point: this package wouldn't work with dependents who want to use ESLint 7 at this moment (see https://github.com/evcohen/eslint-plugin-jsx-a11y/pull/684), because this package is using `node.start`, `node.end`.

**Comment by ljharb** [comment]
Thanks for bearing with me, I see the test failure [here](https://travis-ci.org/github/evcohen/eslint-plugin-jsx-a11y/jobs/685017801).

So, there's two considerations for back compat:
 1. this package should be able to *read* start/end in eslint < 7, just in case. This is pretty easy with something like `const [start, end] = node.range || [node.start, node.end]`.
 1. any objects this package returns to callers should have both range and start/end - this shouldn't matter, since the callers aren't eslint 7.

Does that sound workable?

**Comment by MichaelDeBoey** [comment]
@ljharb I just logged out `start`, `end` & `range` in `getBaseProps` and run tests.

https://github.com/evcohen/jsx-ast-utils/blob/0964cf5471b8157d9f60d4ccf4ca574f98ecfd9c/src/getProp.js#L51-L63

It seems like either `range` or `start` & `end` is passed:

```shell
    console.log src/getProp.js:57
      { range: [ 11, 13 ], start: undefined, end: undefined }
    console.log src/getProp.js:57
      { range: [ 11, 20 ], start: undefined, end: undefined }
    console.log src/getProp.js:57
      { range: undefined, start: 11, end: 13 }
    console.log src/getProp.js:57
      { range: undefined, start: 11, end: 20 }
    console.log src/getProp.js:57
      { range: [ 11, 13 ], start: undefined, end: undefined }
    console.log src/getProp.js:57
      { range: [ 11, 13 ], start: undefined, end: undefined }
    console.log src/getProp.js:57
      { range: [ 11, 13 ], start: undefined, end: undefined }
    console.log src/getProp.js:57
      { range: undefined, start: 11, end: 13 }
    console.log src/getProp.js:57
      { range: undefined, start: 11, end: 13 }
    console.log src/getProp.js:57
      { range: undefined, start: 11, end: 13 }
    console.log src/getProp.js:57
      { range: [ 11, 13 ], start: undefined, end: undefined }
    console.log src/getProp.js:57
      { range: [ 15, 29 ], start: undefined, end: undefined }
    console.log src/getProp.js:57
      { range: [ 11, 29 ], start: undefined, end: undefined }
    console.log src/getProp.js:57
      { range: undefined, start: 11, end: 13 }
    console.log src/getProp.js:57
      { range: undefined, start: 15, end: 29 }
    console.log src/getProp.js:57
      { range: undefined, start: 11, end: 29 }
```

So tests will fail if I change the code to your suggestion
```js
function getBaseProps({
  loc,
  range,
  ...node
}) {
  const [start, end] = range || [node.start, node.end];

  return {
    // ...
  };
}
```

**Comment by ljharb** [comment]
Then it'd be semver-minor to pass both; could we do that?

**Comment by MichaelDeBoey** [comment]
Then we'll have the same as removing them, except we're adding the other missing ones, no? 🤔

So both doing it in code + in the tests?

**Comment by ljharb** [comment]
What I mean is, this package at runtime can provide both forms, by computing the missing ones from the present ones. The tests will use "range" when present, else "start/end".

**Comment by MichaelDeBoey** [comment]
So what you're saying is doing it like this?

```js
function getBaseProps({
  loc,
  range,
  ...node
}) {
  const [start, end] = range || [node.start, node.end];

  return {
    end,
    loc: getBaseLocation(loc),
    range: [start, end],
    start,
  };
}
```

This will create `range` on Nodes that don't have a range and where it's not logical to have a `range` I think.

```shell
    Expected value to deeply and strictly equal to:
      {"end": 24, "loc": {"end": {"column": 24, "line": 1}, "filename": "test.js", "start": {"column": 5, "line": 1}}, "name": {"end": 7, "loc": {"end": {"column": 7, "line": 1}, "filename": "test.js", "start": {"column": 5, "line": 1}}, "name": "id", "start": 5, "type": "JSXIdentifier"}, "start": 5, "type": "JSXAttribute", "value": {"end": 24, "expression": {"end": 23, "expressions": [{"end": 18, "loc": {"end": {"column": 18, "line": 1}, "filename": "test.js", "identifierName": "bar", "start": {"column": 15, "line": 1}}, "name": "bar", "start": 15, "type": "Identifier"}], "loc": {"end": {"column": 23, "line": 1}, "filename": "test.js", "start": {"column": 9, "line": 1}}, "quasis": [{"end": 13, "loc": {"end": {"column": 13, "line": 1}, "filename": "test.js", "start": {"column": 10, "line": 1}}, "start": 10, "tail": false, "type": "TemplateElement", "value": {"cooked": "foo", "raw": "foo"}}, {"end": 22, "loc": {"end": {"column": 22, "line": 1}, "filename": "test.js", "start": {"column": 19, "line": 1}}, "start": 19, "tail": true, "type": "TemplateElement", "value": {"cooked": "baz", "raw": "baz"}}], "start": 9, "type": "TemplateLiteral"}, "loc": {"end": {"column": 24, "line": 1}, "filename": "test.js", "start": {"column": 8, "line": 1}}, "start": 8, "type": "JSXExpressionContainer"}}
    Received:
      {"end": 24, "loc": {"end": {"column": 24, "line": 1}, "filename": "test.js", "start": {"column": 5, "line": 1}}, "name": {"end": 7, "loc": {"end": {"column": 7, "line": 1}, "filename": "test.js", "start": {"column": 5, "line": 1}}, "name": "id", "range": [5, 7], "start": 5, "type": "JSXIdentifier"}, "range": [5, 24], "start": 5, "type": "JSXAttribute", "value": {"end": 24, "expression": {"end": 23, "expressions": [{"end": 18, "loc": {"end": {"column": 18, "line": 1}, "filename": "test.js", "identifierName": "bar", "start": {"column": 15, "line": 1}}, "name": "bar", "start": 15, "type": "Identifier"}], "loc": {"end": {"column": 23, "line": 1}, "filename": "test.js", "start": {"column": 9, "line": 1}}, "quasis": [{"end": 13, "loc": {"end": {"column": 13, "line": 1}, "filename": "test.js", "start": {"column": 10, "line": 1}}, "start": 10, "tail": false, "type": "TemplateElement", "value": {"cooked": "foo", "raw": "foo"}}, {"end": 22, "loc": {"end": {"column": 22, "line": 1}, "filename": "test.js", "start": {"column": 19, "line": 1}}, "start": 19, "tail": true, "type": "TemplateElement", "value": {"cooked": "baz", "raw": "baz"}}], "start": 9, "type": "TemplateLiteral"}, "loc": {"end": {"column": 24, "line": 1}, "filename": "test.js", "start": {"column": 8, "line": 1}}, "range": [8, 24], "start": 8, "type": "JSXExpressionContainer"}}
```

**Comment by ljharb** [comment]
Not unconditionally ofc; where one of range or start+end is present, i would expect both to be.

**Comment by MichaelDeBoey** [comment]
Did some investigation and I came to the following conclusions:

- All tests in `getProp-parser-test` that are using the `flow` parser aren't passing `start` & `end`
- All tests in `getProp-parser-test` that are using the `babel` parser aren't passing `range`
- All tests in `getProp-test` (that are all using the `babel` parser) aren't passing `range` either

This means that the user of `jsx-ast-utils` is already getting different output according to the parser they're using, so I think we should indeed provide both `range` and `start` & `end` for now then.

The ultimate goal would be to remove `start` & `end` from the output imo though.

**Comment by ljharb** [comment]
Totally agree; i'd love to ship a non-major update for this, and then a major update that does nothing except drop start/end and some older eslint versions.

**Comment by MichaelDeBoey** [comment]
On it boss 😉

**Comment by MichaelDeBoey** [comment]
@ljharb This should be OK now 🙂

**Comment by MichaelDeBoey** [comment]
@ljharb Fixed like we said & all green 🎉

**Comment by MichaelDeBoey** [comment]
Ping @ljharb

**Comment by ljharb** [comment]
so, i think this really can't land yet. This repo uses `eslint-config-airbnb-base`, which does not yet support eslint 7. so, that has to be published first (which means `eslint-plugin-import` has to be published first).

I'll rebase and land this once that's done.

**Comment by epmatsw** [comment]
Looks like eslint-plugin-import just published v7 support in ^2.21.0!

**Comment by MichaelDeBoey** [comment]
@ljharb I've updated `eslint-config-airbnb-base`, so I think this one can be merged, no? 🤔

Or is there something else I should do first?

**Pull request merged**
